trigger:
  branches:
    include:
      - main

variables:
- group: swa-secrets

pool:
  vmImage: ubuntu-latest

stages:
- stage: DeployFrontend
  jobs:
    - job: Deploy
      steps:
        - checkout: self

        - task: AzureStaticWebApp@0
          displayName: 'Deploy Frontend to Azure Static Web App'
          inputs:
            app_location: 'frontend'
            output_location: ''
            skip_app_build: true
            deployment_token: $(swa_deployment_token)
