trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroup: 'projet-azure-rg'
  swaName: 'projet-azure-frontend'
  location: 'France Central'

stages:
- stage: Deploy
  jobs:
  - deployment: DeployFullStack
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: AzureCLI@2
              inputs:
                azureSubscription: 'SERVICE-CONNECTION-AZURE'
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az staticwebapp upload \
                    --name $(swaName) \
                    --resource-group $(resourceGroup) \
                    --source ./frontend \
                    --api ./api \
                    --location "$(location)"
