trigger:
  branches:
    include:
      - main

variables:
  - name: azureSubscription
    value: 'AzureSPN'
  - name: resourceGroup
    value: 'projet-azure-rg'
  - name: apiAppName
    value: 'projet-azure-api'
  - name: keyVaultName
    value: 'projet-azure-kv'

stages:
- stage: BuildAndTest
  displayName: ' Build & Test'
  jobs:
  - job: BuildBackend
    displayName: 'Install Python dependencies'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
      - script: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'pip install'

- stage: Deploy
  displayName: ' Deploy to Azure'
  dependsOn: BuildAndTest
  jobs:
  - deployment: DeployAPI
    displayName: 'Deploy Flask App'
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              displayName: 'Azure Web App Deploy'
              inputs:
                azureSubscription: $(azureSubscription)
                appType: webAppLinux
                appName: $(apiAppName)
                package: 'backend'
                startupCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'
            - task: AzureCLI@2
              displayName: 'Set KEYVAULT_NAME app setting'
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az webapp config appsettings set \
                    -g $(resourceGroup) \
                    -n $(apiAppName) \
                    --settings KEYVAULT_NAME=$(keyVaultName)
