trigger:
  branches:
    include:
      - main

variables:
- group: swa-secrets

jobs:
- job: DeployFrontend
  displayName: Deploy Frontend to Azure Static Web App
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self

    - task: AzureStaticWebApp@0
      displayName: Deploy to SWA
      inputs:
        app_location: 'frontend'
        output_location: ''
        api_location: ''
        skip_app_build: true
        deployment_token: $(swa_deployment_token)

- job: DeployFunction
  displayName: Deploy Azure Function API
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self

    - task: ArchiveFiles@2
      displayName: Archive function app for deployment
      inputs:
        rootFolderOrFile: 'api'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - task: AzureFunctionApp@1
      displayName: Deploy Function App
      inputs:
        azureSubscription: 'AzureSPN'
        appType: functionAppLinux
        appName: 'projet-azure-api' 
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
