trigger:
  branches:
    include:
      - main

variables:
  - group: SWA
  - name: azureSubscription
    value: 'AzureSPN'  
  - name: staticWebAppLocation
    value: 'src/frontend'
  - name: functionAppLocation
    value: 'src/functions'
  - name: functionAppName
    value: 'projet-azure-backend'
  - name: deployment_token
    value: $(deployment_token)

stages:
- stage: BuildAndDeploy
  jobs:
  - job: DeployFullStack
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: AzureStaticWebApp@0
      displayName: 'Deploy Frontend to Azure Static Web App'
      inputs:
        app_location: $(staticWebAppLocation)
        skip_app_build: true
        azure_static_web_apps_api_token: $(deployment_token)

    - task: ArchiveFiles@2
      displayName: 'Archive Azure Function App'
      inputs:
        rootFolderOrFile: $(functionAppLocation)
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - task: AzureFunctionApp@1
      displayName: 'Deploy Function App (Backend)'
      inputs:
        azureSubscription: $(azureSubscription)
        appType: functionAppLinux
        appName: $(functionAppName)
        package: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
