trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'AzureSPN'
  resourceGroup:     'projet-azure-rg'
  apiAppName:        'projet-azure-api'
  keyVaultName:      'projet-azure-kv'

stages:
- stage: Build
  displayName: "🛠️ Build backend"
  jobs:
  - job: BuildBackend
    displayName: "Install Python deps"
    pool:
      vmImage: ubuntu-latest
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'

      - script: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: "pip install"

- stage: Deploy
  displayName: "🚀 Deploy backend"
  dependsOn: Build
  jobs:
  - deployment: DeployAPI
    displayName: "Deploy Flask App to App Service"
    environment: 'production'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: AzureWebApp@1
              displayName: "Azure Web App Deploy"
              inputs:
                azureSubscription: $(azureSubscription)
                appType: webAppLinux
                appName: $(apiAppName)
                package: '$(System.DefaultWorkingDirectory)/backend'
                startupCommand: 'gunicorn --bind=0.0.0.0 --timeout 600 app:app'

            - task: AzureCLI@2
              displayName: "Configure KEYVAULT_NAME setting"
              inputs:
                azureSubscription: $(azureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az webapp config appsettings set \
                    -g $(resourceGroup) \
                    -n $(apiAppName) \
                    --settings KEYVAULT_NAME=$(keyVaultName)
