trigger:
  - main

variables:
  azure_static_web_apps_api_token: $(deployment_token)

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureStaticWebApp@0
    inputs:
      app_location: "/frontend"
      api_location: ""  # Vide car backend séparé
      output_location: ""  # Pas de build
      azure_static_web_apps_api_token: $(azure_static_web_apps_api_token)
